name: example
on: push
jobs: 
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: <first job>
        run: echo hello world
  compilecode:
    runs-on: ubuntu-latest
    steps:
      - name: <make job>
        run: skim.sh

