name: example
on: push
jobs: 
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: <first job>
        run: echo hello world
  compilecode:
    runs-on: ubuntu-latest
    container: rootproject/root-conda:6.18.04
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
      - name: <make job>
        run: ./skim.sh
  compilecode_latest:
    runs-on: ubuntu-latest
    container: rootproject/root-conda:latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
      - name: <make_latest job>
        run: ./skim.sh


