name: example
on: push
jobs: 
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: <first job>
        run: echo hello world
  compilecode:
    runs-on: ubuntu-latest
    container: rootproject/root-conda:${{ matrix.version }}
    strategy:
      matrix:
        version: [6.18.04, latest]
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
      - name: <make job>
        run: ./skim.sh

